<a href="https://colab.research.google.com/github/wcliao1962/2025_DL_hws/blob/main/hw6_2_%E5%8F%83%E8%80%83%E7%AD%94%E6%A1%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# hw6-2


## hw6-2_第2題 (參考冒險旅程 26)

因為等下會需要模擬神經元的計算，所以需要我們的老朋友`NumPy`

In [ ]:
import numpy as np

#### 1. 一起回憶一下在冒險19 學到的一個RNN 神經元的架構，寫一個小程式模擬神經元的運算。假設輸入是三個字，起始隱藏狀態是零向量，自己設定起始權重和偏移值，計算$ h_{1} $。

因為RNN神經元使用的激發函數是 $ \text{tanh} $ ，而老朋友`Numpy`已經有寫好的函式可以用：`np.tanh()`...     
我們就直接開始計算吧！

假設RNN起始隱藏狀態 $ \mathbf{h_{0}} $ 是零向量：

In [ ]:
h0 = np.array([0, 0, 0, 0])
h0

array([0, 0, 0, 0])

假設輸入是三個字：x1, x2, x3

In [ ]:
X = np.random.randint(0, 10, size=(3,3))
X

array([[0, 6, 6],
       [6, 1, 4],
       [3, 6, 6]])

In [ ]:
x1 = X[0]
x2 = X[1]
x3 = X[2]

In [ ]:
x1, x2, x3

(array([0, 6, 6]), array([6, 1, 4]), array([3, 6, 6]))

假設起始權重和偏移值分別為：     
$W^{x}=
\left[
\begin{matrix}
1 & -1 & 0 & 0.5 \\
2 & 0  &-1 & 3\\
1.5 & 1& 2 & 1
\end{matrix}
\right]$、
$W^{h} =
\left[
\begin{matrix}
1.2 & 0.3 &0.1 & 0.6  \\
0.4 & 2 & 1 & 0.1 \\
0.2 & 1.3 &0.7 & 1.6  \\
2.4 & 0.2 &0.1 & 0.7
\end{matrix}
\right]$、
$b=
\left[
\begin{matrix}
0.3 \\
0.8 \\
0.5 \\
0.2
\end{matrix}
\right]$

In [ ]:
Wx = np.array([[1, -1, 0, 0.5], [2, 0, -1, 3], [1.5, 1, 2, -1]])
Wh = np.array([[1.2, 0.3, 0.1, 0.6], [0.4, 2, 1, 0.1], [0.2, 1.3, 0.7, 1.6], [2.4, 0.2, 0.1, 0.7]])
b = np.array([0.3, 0.8, 0.5, 0.2])

$ h_{1} = \sigma (x_{1}W^{x} + h_{0}W^{h} + b) $

先計算出激發函式裡的矩陣計算，計算結果叫 $ z_{1} $：     
$ z_1= x_{1}W^{x} + h_{0}W^{h} + b $

In [ ]:
# 給x1, h0
z1 = np.dot(x1, Wx) + np.dot(h0, Wh) + b
z1

array([21.3,  6.8,  6.5, 12.2])

最後，$ h_{1} = \sigma (z_1) $

In [ ]:
h1 = np.tanh(z1)
h1

array([1.        , 0.99999752, 0.99999548, 1.        ])

#### 2. 再做一次RNN，算出計算$ h_{2} $。記得RNN 神經元使用的激發函數是tanh 喔！

$ h_{2} = \sigma (x^{2}_{t}W^{x} + h_{1}W^{h} + b) $

先算出激發函式裡的那一串，叫 $ z_2 $：     
$ z_2 = w^{x}x^{2}_{t} + w^{h}h_{1} + b $

In [ ]:
# 給x2, h1
z2 = np.dot(x2, Wx) + np.dot(h1, Wh) + b
z2

array([18.4999981 ,  2.59998916,  9.39999435,  5.19999252])

最後，$ h_{2} = \sigma (z_{h_{2}}) $

In [ ]:
h2 = np.tanh(z2)
h2

array([1.        , 0.98902717, 0.99999999, 0.99993914])

#### 3. 計算計算$ h_{1} $

In [ ]:
# 給x3, h2
z3 = np.dot(x3, Wx) + np.dot(h2, Wh) + b
z3

array([28.49546479,  7.57804214,  8.38902107, 16.69886009])

In [ ]:
h3 = np.tanh(z3)
h3

array([1.        , 0.99999948, 0.9999999 , 1.        ])

=============================================================

## hw6-2_第3題 (參考冒險旅程 27)

In [ ]:
S3 = np.array([2, 5, 3, 1])
S3

array([2, 5, 3, 1])

#### 計算注意力強度的向量 $ e = [e_1, e_2, e_3] $，再經過 `softmax`函數轉換成 $ \alpha $。

In [ ]:
e1 = np.dot(S3, h1)
e2 = np.dot(S3, h2)
e3 = np.dot(S3, h3)
e = np.array([e1, e2, e3])
e

array([10.99997403, 10.94507492, 10.99999707])

### Softmax 函式

$ x = (x_1, x_2, ..., x_n) $

$ \text{Softmax}(x_j) = \cfrac{e^{x_j}}{\sum_{k=1}^{n} e^{x_k}} \text{, } j = 1,...,n $

In [ ]:
def softmax_0(x): # x是一個向量
    c=np.max(x)
    x = x - c
    return np.exp(x) / np.sum(np.exp(x))

In [ ]:
def softmax(x): # x 可以是一個向量或矩陣(多個向量)
    x = x - np.max(x, axis=-1, keepdims=True)
    return np.exp(x) / np.sum(np.exp(x), axis=-1, keepdims=True)

#### 注意注意力強度e轉換為$\alpha$

In [ ]:
alpha = softmax(e)
alpha

array([0.33937377, 0.32124464, 0.33938159])

#### 計算Decoder在t=3所使用的$c_3$

In [ ]:
h = np.array([h1, h2, h3])

In [ ]:
c3 = np.dot(alpha, h)
c3

array([1.        , 0.99647402, 0.99999843, 0.99998045])

==========================================================================

## hw6-2_第4題 (參考冒險旅程 28)


$W^{Q}=
\left[
\begin{matrix}
0 & 0 & 1  \\
1 & 0 & 0 \\
0 & 0 & 1
\end{matrix}
\right]$、
$W^{K} =
\left[
\begin{matrix}
1 & 0 & 1  \\
0 & 1 & 1 \\
0 & 1 & 0
\end{matrix}
\right]$、
$W^{V}=
\left[
\begin{matrix}
0 & 2 & 1  \\
1 & 0 & 3 \\
1 & 0 & 1
\end{matrix}
\right]$

In [ ]:
WQ = np.array([[0, 0, 1], [1, 0, 0], [0, 0, 1]])
WK = np.array([[1, 0, 1], [0, 1, 1], [0, 1, 0]])
WV = np.array([[0, 2, 1], [1, 0, 3], [1, 0, 1]])

In [ ]:
Q = np.dot(X, WQ)
Q

array([[ 6,  0,  6],
       [ 1,  0, 10],
       [ 6,  0,  9]])

In [ ]:
K = np.dot(X, WK)
K

array([[ 0, 12,  6],
       [ 6,  5,  7],
       [ 3, 12,  9]])

In [ ]:
V = np.dot(X, WV)
V

array([[12,  0, 24],
       [ 5, 12, 13],
       [12,  6, 27]])

#### 定義Attention函數 & 給Q, K, V，進行self-attention計算

In [ ]:
def Attention (Q, K, V):
  d = 3
  return np.dot(softmax(np.dot(Q, K.T) / np.sqrt(d)), V)

In [ ]:
att = Attention(Q, K, V)
att

array([[ 5.21245763, 11.81789346, 13.42491526],
       [11.99961762,  6.00032772, 26.99923523],
       [ 8.5       ,  9.        , 20.        ]])

In [ ]:
c1 = att[0]
c1

array([ 5.21245763, 11.81789346, 13.42491526])

In [ ]:
c2 = att[1]
c2

array([11.99961762,  6.00032772, 26.99923523])

In [ ]:
c3 = att[2]
c3

array([ 8.5,  9. , 20. ])